### ISSUE TITLE
README file todo list

### ISSUE THREAD

**Issue by vdevauxchupin** [vdevauxchupin/ITS_LIVE_TOOL#16]
- [x] Instructions to install the package (pip git+https, and maybe later just pip) 
- [ ] Flowchart (https://app.diagrams.net/)
- [ ] Gif showing how the GUI works
- [ ] Links to notebooks
- [ ] Links to pages on the documentation

**Comment by e-marshall** [comment]
adding some more:
methods refs

- [ ] methods references
- [ ] software references
- [ ] data and scripts (from itslive)
- [ ] data (RGI outlines, OGGM centerlines)

**Comment by e-marshall** [comment]
Readme is currently automatically generated off of index.ipynb in nbdev. change this so that index.ipynb becomes roadmap.ipynb and readme is a markdown file instead of coming from a ipynb

**Comment by e-marshall** [comment]
best way to cite software used? do we need to manually do it for every package used ?
